### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#319]
I dont know how reproduce, because im not there, but i have the console error with bt full:
```
Luiis Da Tankz has logged out.

Lua Script Error: [Npc interface]
data/npc/scripts/Esrik.lua:onCreatureAppear
 value

Lua Script Error: [Npc interface]
data/npc/scripts/Esrik.lua:onCreatureAppear
Stack size changed!
Luiis Da Tankz has logged in.

Program received signal SIGSEGV, Segmentation fault.
0x00006e34843ab0bd in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
(gdb) bt full

#0  0x00006e34843ab0bd in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#1  0x00006e348439efbc in lua_next () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#2  0x00006e34843aef3a in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#3  0x00006e34843aef71 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#4  0x00006e34843af031 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#5  0x00006e34843af64b in luaL_traceback () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#6  0x00006e34843b2d58 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#7  0x00006e34843a261d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#8  0x00006e34843a297d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#9  0x00006e348439ebc8 in lua_callk () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#10 0x000000000065ba5b in LuaScriptInterface::getStackTrace (this=0x6e34601df540,
    error_desc="attempt to concatenate a table value")
    at /home/Testera_1312_OTX/source/src/luascript.cpp:418
No locals.
#11 0x000000000065be76 in LuaScriptInterface::luaErrorHandler (L=0x19bdc40)
    at /home/Testera_1312_OTX/source/src/luascript.cpp:503
        errorMessage = "attempt to concatenate a table value"
        interface = 0x6e34601df540
        __PRETTY_FUNCTION__ = "static int LuaScriptInterface::luaErrorHandler(lua_State*)"
#12 0x00006e34843a261d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#13 0x00006e34843a297d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#14 0x00006e34843a199f in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#15 0x00006e34843a1adf in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#16 0x00006e34843a1b4a in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#17 0x00006e34843a1c54 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#18 0x00006e34843ad238 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#19 0x0000000000000010 in ?? ()
No symbol table info available.
#20 0x00007be23a479940 in ?? ()
No symbol table info available.
#21 0x0000000000000058 in ?? ()
No symbol table info available.
#22 0x0000000000000000 in ?? ()
---Type <return> to continue, or q <return> to quit---
```
I use the last commit.

**Comment by westwol** [comment]
Keep writting bt full to see full log.

**Comment by Eternal-Scripts** [comment]
Please, take a full log in next time.

**Comment by darkjav** [comment]
@Eternal-Scripts 
How take a full log? I know that only is "bt full". Please explain me. Thanks.

**Comment by Eternal-Scripts** [comment]
---Type <return> to continue, or q <return> to quit---
press return "enter"
