### ISSUE TITLE
Server crash, problem with eventPlayerOnLook 

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#584]
Along time ago i report here: https://github.com/malucooo/Otxserver-New/issues/444
but still happening:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x6dc66d643700 (LWP 12649)]
0x00006dc66ed1d853 in std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char,
 std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char>
 >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt full
#0  0x00006dc66ed1d853 in std::basic_ostream<char, std::char_traits<char> >& std::operator<< <c
har, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<c
har> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#1  0x0000000000747829 in Player::getDescription (this=0x6dc514c3ba60, lookDistance=2)
    at /ssd/Testera_1140_13/source/src/player.cpp:175
        memberCount = 120699044248988
        s = <incomplete type>
#2  0x00000000006bdd85 in LuaScriptInterface::luaCreatureGetDescription (L=0x2381fd0)
    at /ssd/Testera_1140_13/source/src/luascript.cpp:7606
        distance = 2
        creature = 0x6dc514c3ba60
#3  0x00006dc66fa7b61d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#4  0x00006dc66fa869b4 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#5  0x00006dc66fa7b989 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#6  0x00006dc66fa7afac in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#7  0x00006dc66fa7bbc1 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#8  0x00006dc66fa77c9d in lua_pcallk () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#9  0x000000000065cb96 in LuaScriptInterface::protectedCall (L=0x2381fd0, nargs=4, nresults=0)
    at /ssd/Testera_1140_13/source/src/luascript.cpp:287
        error_index = 5
        ret = 0
#10 0x000000000065da9d in LuaScriptInterface::callVoidFunction (this=0x6dc6691f8d50, params=4)
    at /ssd/Testera_1140_13/source/src/luascript.cpp:529
        size = 9
#11 0x00000000005a70ca in Events::eventPlayerOnLook (this=0x6dc6691f8d50,
    player=0x6dc5140407e0, position=..., thing=0x6dc514c3ba60, stackpos=1 '\001',
    lookDistance=2) at /ssd/Testera_1140_13/source/src/events.cpp:386
        env = 0xb9eb80 <LuaScriptInterface::scriptEnv>
        L = 0x2381fd0
#12 0x00000000005bd7d1 in Game::playerLookAt (this=0xb9f780 <g_game>, playerId=268439326,
    pos=..., stackPos=1 '\001') at /ssd/Testera_1140_13/source/src/game.cpp:3054
        thingPos = {x = 32367, y = 32181, z = 7 '\a'}
        playerPos = {x = 32367, y = 32183, z = 7 '\a'}
        lookDistance = 2
        player = 0x6dc5140407e0
        thing = 0x6dc514c3ba60
#13 0x00000000007a7692 in std::_Mem_fn<void (Game::*)(unsigned int, Position const&, unsigned char)>::operator()<unsigned int&, Position&, unsigned char&, void> (this=0x239f4c0,
    __object=0xb9f780 <g_game>) at /usr/include/c++/4.8/functional:601
No locals.
#14 0x00000000007a3626 in std::_Bind<std::_Mem_fn<void (Game::*)(unsigned int, Position const&, unsigned char)> (Game*, unsigned int, Position, unsigned char)>::__call<void, , 0ul, 1ul, 2ul,---Type <return> to continue, or q <return> to quit---
 3ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) (this=0x239f4c0,
    __args=<unknown type in /ssd/Testera_1140_13/tfs, CU 0x1775810, DIE 0x189dfe2>)
    at /usr/include/c++/4.8/functional:1296
No locals.
#15 0x000000000079e0fc in std::_Bind<std::_Mem_fn<void (Game::*)(unsigned int, Position const&, unsigned char)> (Game*, unsigned int, Position, unsigned char)>::operator()<, void>() (
    this=0x239f4c0) at /usr/include/c++/4.8/functional:1355
No locals.
#16 0x0000000000793848 in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (Game::*)(unsigned int, Position const&, unsigned char)> (Game*, unsigned int, Position, unsigned char)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/4.8/functional:2071
No locals.
#17 0x00000000007e5ada in std::function<void ()>::operator()() const (this=0x23fc300)
    at /usr/include/c++/4.8/functional:2471
No locals.
#18 0x00000000007e59c4 in Task::operator() (this=0x23fc2f0)
    at /ssd/Testera_1140_13/source/src/tasks.h:40
No locals.
#19 0x00000000007e51c0 in Dispatcher::threadMain (this=0xb9f5e0 <g_dispatcher>)
    at /ssd/Testera_1140_13/source/src/tasks.cpp:60
        task = 0x23fc2f0
        taskLockUnique = {_M_device = 0xb9f5f8 <g_dispatcher+24>, _M_owns = false}
#20 0x00000000007369c5 in std::_Mem_fn<void (Dispatcher::*)()>::operator()<, void>(Dispatcher*) const (this=0x23bdb58, __object=0xb9f5e0 <g_dispatcher>)
    at /usr/include/c++/4.8/functional:601
No locals.
#21 0x0000000000736341 in std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x23bdb50)
    at /usr/include/c++/4.8/functional:1732
No locals.
#22 0x0000000000735c2b in std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)>::operator()() (this=0x23bdb50) at /usr/include/c++/4.8/functional:1720
No locals.
#23 0x0000000000735628 in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)> >::_M_run() (this=0x23bdb38) at /usr/include/c++/4.8/thread:115
No locals.
#24 0x00006dc66ed3ba60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#25 0x00006dc66ef96184 in start_thread (arg=0x6dc66d643700) at pthread_create.c:312
        __res = <optimised out>
        pd = 0x6dc66d643700
        now = <optimised out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {120699006236416, 3256763214580779531, 1,
                0, 120699006237120, 120699006236416, -666952572948084213,
                -666949383652144629}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0,
              0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimised out>
        pagesize_m1 = <optimised out>
        sp = <optimised out>
        freesize = <optimised out>
---Type <return> to continue, or q <return> to quit---
        __PRETTY_FUNCTION__ = "start_thread"
#26 0x00006dc66e4a337d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.
```

**Comment by Eternal-Scripts** [comment]
You source isn't the original OTX, please test with this repository.
