### ISSUE TITLE
Crash again - bt full

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#658]
Hi, minutes ago the server crashed, i don't know how to reproduce,
is sure that is a different problem, not related to the another issue that i report.

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x703e05d07700 (LWP 8130)]
0x0000703e073436ad in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt full
#0  0x0000703e073436ad in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#1  0x0000703e073a3529 in std::string::assign(std::string const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#2  0x00000000006c1218 in LuaScriptInterface::luaPlayerSetPreyName (L=0x34d8ff0)
    at /ssd/Testera_1149/source/src/luascript.cpp:8757
        column = 6
        name = ""
        player = 0x703d040b8980
#3  0x0000703e080d961d in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#4  0x0000703e080e49b4 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#5  0x0000703e080d9989 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#6  0x0000703e080d8fac in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#7  0x0000703e080d9bc1 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#8  0x0000703e080d5c9d in lua_pcallk () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#9  0x000000000065cde4 in LuaScriptInterface::protectedCall (L=0x34d8ff0, nargs=3, nresults=0)
    at /ssd/Testera_1149/source/src/luascript.cpp:287
        error_index = 5
        ret = 0
#10 0x000000000065dceb in LuaScriptInterface::callVoidFunction (this=0x703e0145a180, params=3)
    at /ssd/Testera_1149/source/src/luascript.cpp:529
        size = 8
#11 0x00000000006f1a49 in Module::executeOnRecvbyte (this=0x703e00d0bfe0,
    player=0x703d040b8980, msg=...) at /ssd/Testera_1149/source/src/modules.cpp:181
        env = 0xb9fb40 <LuaScriptInterface::scriptEnv>
        L = 0x34d8ff0
#12 0x00000000006f1532 in Modules::executeOnRecvbyte (this=0x703e0145a140,
    player=0x703d040b8980, msg=..., byte=235 '\353')
    at /ssd/Testera_1149/source/src/modules.cpp:89
        module = 0x703e00d0bfe0
        it = @0x703e010a9bd0: {first = 235 '\353', second = 0x703e00d0bfe0}
Python Exception <class 'IndexError'> list index out of range:
        __for_range = std::map with 13 elements
        __for_begin = {first = 235 '\353', second = }
        __for_end = {first = 13 '\r', second = <vtable for LuaScriptInterface+16>}
#13 0x00000000007a3208 in std::_Mem_fn<void (Modules::*)(Player*, NetworkMessage&, unsigned char)>::operator()<Player*&, NetworkMessage&, unsigned char&, void> (this=0x3642900,
    __object=0x703e0145a140) at /usr/include/c++/4.8/functional:601
No locals.
#14 0x000000000079d934 in std::_Bind<std::_Mem_fn<void (Modules::*)(Player*, NetworkMessage&, unsigned char)> (Modules*, Player*, NetworkMessage, unsigned char)>::__call<void, , 0ul, 1ul, 2ul, 3ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) (this=0x3642900,
    __args=<unknown type in /ssd/Testera_1149/tfs, CU 0x16f2369, DIE 0x181ab48>)
    at /usr/include/c++/4.8/functional:1296
---Type <return> to continue, or q <return> to quit---
No locals.
#15 0x000000000079109e in std::_Bind<std::_Mem_fn<void (Modules::*)(Player*, NetworkMessage&, unsigned char)> (Modules*, Player*, NetworkMessage, unsigned char)>::operator()<, void>() (
    this=0x3642900) at /usr/include/c++/4.8/functional:1355
No locals.
#16 0x000000000078526a in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (Modules::*)(Player*, NetworkMessage&, unsigned char)> (Modules*, Player*, NetworkMessage, unsigned char)> >::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/include/c++/4.8/functional:2071
No locals.
#17 0x00000000007e6138 in std::function<void ()>::operator()() const (this=0x38d6060)
    at /usr/include/c++/4.8/functional:2471
No locals.
#18 0x00000000007e6022 in Task::operator() (this=0x38d6050)
    at /ssd/Testera_1149/source/src/tasks.h:40
No locals.
#19 0x00000000007e581e in Dispatcher::threadMain (this=0xba05a0 <g_dispatcher>)
    at /ssd/Testera_1149/source/src/tasks.cpp:60
        task = 0x38d6050
        taskLockUnique = {_M_device = 0xba05b8 <g_dispatcher+24>, _M_owns = false}
#20 0x0000000000736e79 in std::_Mem_fn<void (Dispatcher::*)()>::operator()<, void>(Dispatcher*)
 const (this=0x3514ba8, __object=0xba05a0 <g_dispatcher>)
    at /usr/include/c++/4.8/functional:601
No locals.
#21 0x00000000007367f5 in std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)>
::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x3514ba0)
    at /usr/include/c++/4.8/functional:1732
No locals.
#22 0x00000000007360df in std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)>
::operator()() (this=0x3514ba0) at /usr/include/c++/4.8/functional:1720
No locals.
#23 0x0000000000735adc in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*
)()> (Dispatcher*)> >::_M_run() (this=0x3514b88) at /usr/include/c++/4.8/thread:115
No locals.
#24 0x0000703e07399a60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#25 0x0000703e075f4184 in start_thread (arg=0x703e05d07700) at pthread_create.c:312
        __res = <optimised out>
        pd = 0x703e05d07700
        now = <optimised out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {123411687831296, 1325738115427917572, 1,
                0, 123411687832000, 123411687831296, -1001491908196376828,
                -1001495164530925820}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0,
              0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimised out>
        pagesize_m1 = <optimised out>
        sp = <optimised out>
        freesize = <optimised out>
        __PRETTY_FUNCTION__ = "start_thread"
#26 0x0000703e06b0137d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
---Type <return> to continue, or q <return> to quit---
No locals.
```

**Comment by Eternal-Scripts** [comment]
Try reproduce that in our otx repository with last commit. I will put unconfirmed you have only 24 hours to do it.

**Comment by EnzzoCaaue** [comment]
Could not reproduce either. You should consider upgrade your kernel.

**Comment by darkjav** [comment]
@EnzzoCaaue To what version?

**Comment by EnzzoCaaue** [comment]
@darkjav to newest version available.
